server:
  port: 8092

spring:
  application:
    name: core-banking-service
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_service
    username: root
    password: admin123!
  jpa:
    hibernate:
      ddl-auto: none

info:
  app:
    name: ${spring.application.name}